val command_result : Normal.Command_result.t -> Yojson.Safe.t
val command_result_string : Normal.Command_result.t -> string
val observation : Normal.Observation.t -> Yojson.Safe.t
val origin : Normal.Origin.t -> Yojson.Safe.t
val region : Normal.Region.t -> Yojson.Safe.t
val region_address : Normal.Region_address.t -> Yojson.Safe.t
val region_ref : Normal.Region_ref.t -> Yojson.Safe.t
val origin_scoped_id : Normal.Origin_scoped_id.t -> Yojson.Safe.t
val reference : Normal.Reference.t -> Yojson.Safe.t
val annotation : Normal.Annotation.t -> Yojson.Safe.t
val annotation_occurrence : Normal.Annotation_occurrence.t -> Yojson.Safe.t
val reference_definition : Normal.Reference_definition.t -> Yojson.Safe.t
val reference_use : Normal.Reference_use.t -> Yojson.Safe.t
val sidecar_snapshot : Normal.Sidecar_snapshot.t -> Yojson.Safe.t
val coverage : Normal.Coverage.t -> Yojson.Safe.t
val diagnostic : Normal.Diagnostic.t -> Yojson.Safe.t
val selector : Normal.Selector.t -> Yojson.Safe.t
val patch : Normal.Patch.t -> Yojson.Safe.t
val workspace_snapshot : Normal.Workspace_snapshot.t -> Yojson.Safe.t
