(lang dune 3.10)
(name monika_sugar)
(generate_opam_files true)

(package
 (name monika_sugar)
 (synopsis "Monika reference implementation")
 (description
  "Reference implementation of Monika's typed observation, auditing, derivation, and patch-application contracts.")
 (homepage "https://github.com/KijitoraFinch/Mitoujr_Alpha")
 (bug_reports "https://github.com/KijitoraFinch/Mitoujr_Alpha/issues")
 (source
  (github KijitoraFinch/Mitoujr_Alpha))
 (depends
  (ocaml (>= 5.2))
  dune
  dune-build-info
  cmarkit
  ptime
  yaml
  yojson
  digestif
  (alcotest :with-test)
  (qcheck-alcotest :with-test)))
